### ISSUE TITLE
datepicker is broken on IE11

### ISSUE THREAD

**Issue by jwesselink** [carbon-design-system/carbon-components-angular#1613] opened 2020-11-16 11:47 UTC
## Detailed description

> Describe in detail the issue you're having.

The datepicker does not seem to work on IE11. The console is flooded by errors because Element.closest function is used and that is not supported by IE https://caniuse.com/element-closest (see carbon-flatpickr-month-select.ts)

I tried to fix it using a polyfill (https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill), this fixes the errors, but the datepicker still doesn't function properly (see screenshot)

<img width="388" alt="Screenshot 2020-11-16 at 12 07 01" src="https://user-images.githubusercontent.com/2271922/99248574-f9c1a900-2808-11eb-8e58-d4a044cd3244.png">

I also tested the pure datepicker from flatpickr (https://flatpickr.js.org/examples/) and that seems to work fine on IE11, so the issue seems to be in angular-carbon.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Datepicker

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

4.21.0

We are currently working on a project that must be finished in Q1 2021. Internet Explorer 11 support is important to us because 30% of the users are still using it. One of the main reasons why we chose carbon, is because of the IE11 support

**Comment by cal-smith** [comment] 2020-11-16 16:23
Can you create a minimal reproduction (`ng new testapp` and push it to a github repo)? I'm not sure at the moment where the issue would be coming from ... We may need to update flatpickr, or it could be something in the styles that IE doesn't like

**Comment by jwesselink** [comment] 2020-11-16 17:54
Hi, thanks for the reply!

I've created this repo to reproduce the issue: 
https://github.com/jwesselink/carbon-datepicker

Run `npm run start:ie` to start

When running the above project in IE11, the console will be flooded with errors about Element.closest and probably crash IE

I've also created a branch named [closest-polyfill](https://github.com/jwesselink/carbon-datepicker/tree/closest-polyfill). This includes the polyfill for Element.closest and results in the broken datepicker as shown on the screenshot.

**Comment by cal-smith** [comment] 2020-11-17 02:14
Thanks so much! I'll pull that and dig around a bit 👍

**Comment by jwesselink** [comment] 2020-12-15 08:23
Hi, any news on this issue?

**Comment by cal-smith** [comment] 2021-01-06 20:09
Sorry! Nothing yet ... IE is a real pain to debug in 😅

**Comment by Akshat55** [comment] 2023-08-28 19:44
Closing issue, since IE is deprecated and Edge is chromium based. I don't see any point in resolving this issue since Carbon no longer supports IE.😅

**Closed by Akshat55** 2023-08-28 19:44 UTC
Labels: bug, IE11, component: Date Picker
