### ISSUE TITLE
[Bug]: tooltip issues in toolbar of data table  

### ISSUE THREAD

**Issue by lionriver** [carbon-design-system/carbon-components-angular#2626] opened 2023-07-06 08:10 UTC
### Package

carbon-components

### Browser

Chrome, Firefox, Edge

### Package version

10.58.3

### Description

Tooltip in table toolbar issues:
1> icon in table header displayed over tooltip for action button
2> tooltip text can only displayed in one line.

### Reproduction/example

https://codesandbox.io/p/sandbox/optimistic-river-sd3q2p?file=%2Fsrc%2Fapp%2Fapp.component.html%3A28%2C59

### Steps to reproduce

1) select one or more items in table
2) hover on toolbar action button to show the tooltips

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by lionriver** [comment] 2023-07-07 08:43
For issue #2, it is caused by the clip path. Once you remove the clip, you will be able to see the full tooltip in multi lines but this will bring unwanted behavior where actions toolbar will not close. By the looks of it, the toolbar action doesn't support a lot of popover functionality due to clip path

**Comment by Akshat55** [comment] 2023-07-12 01:56
Hey @tay1orjones, this issue is for `@carbon/styles` and `carbon-components`, not `carbon-components-angular`. The issue is that clip-path style property trims tooltips (icon button/tooltip/popover/etc.) when used in Table Batch Actions. 

Ex.
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/38994122/363d4cf7-0654-4749-b80c-5fbe653fffeb)

This issue is caused by clip path and as stated by @lionriver, once we remove the clip path, we can see the full tooltip. Is there a work around or design guidance on using tooltip with table toolbar actions? In React, I don't see the option to add tooltips to batch actions, so not sure if it's supported.

Let me know whether I should transfer this issue back since it's a styles related issue.

**Comment by Akshat55** [comment] 2023-08-28 19:33
Closing this issue since this is a duplicate of #2625. There are prototypes being created to resolve this issue using Floating-UI,

**Closed by Akshat55** 2023-08-28 19:33 UTC
