### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cnestor1** [carbon-design-system/carbon-components-angular#2561] opened 2023-05-22 21:05 UTC
### Package

@carbon/icons

### Browser

Chrome

### Package version

"@carbon/icons": "11.17.0",
 "carbon-components-angular": "4.73.3",

### React version

ANGULAR 16

### Description

  Angular 16 is not supported:
```
  node_modules/carbon-components-angular/icon/icon.module.d.ts:29:22
    29 export declare class IconModule {
                            ~~~~~~~~~~
    This likely means that the library (carbon-components-angular) which declares IconModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

No Usage of ngcc
In Angular version 9, Angular switched from its old view engine to ivy.

Angular Compatibility Compiler (ngcc) was designed to support libraries that continued to use the outdated view engine. The ngcc has been eliminated in version 16 along with all other view engine-related codes. As a result, Angular View Engine libraries cannot be utilized in v16+ and the Angular Bundle side should be reduced. Although this is a hard break in compatibility, such libraries were not officially supported.

When will a new version of the @Cabon/icons library compatible with Angular 16 be published? 

### Reproduction/example

n/a

### Steps to reproduce

n/a

### Suggested Severity

None

### Application/PAL

ZAA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Akshat55** [comment] 2023-05-23 13:21
Angular 16 is NOT supported as of yet. In Angular 16, ngcc was removed which enabled teams to use View Engine with angular. 

Carbon Angular 5 (Carbon 11) will be released by end of Q2 which will support Angular 16.

**Comment by cnestor1** [comment] 2023-05-23 14:44
Thanks but is that a firm statement?  
If we commit to Carbon-design we will be stuck with Angular 15 until Carbon 5 is released.  I don't want to be in a situation where there is a PSIRT forcing us to upgrade to Angular 16 and we have to switch the UI from Carbon Design to Angular Material for example.

**Comment by ugarciacisive** [comment] 2023-06-05 19:25
@Akshat55 - Q2 ends in a phew weeks I understand you will be updating to v5 and Carbon 11 and you will include support for A16. Are you publishing this update somewhere?

**Comment by Akshat55** [comment] 2023-06-22 15:27
@seriouz You should still be able to use it, we just need to add Angular 16 as peer dependency. https://github.com/carbon-design-system/carbon-components-angular/pull/2605 This PR will do so

**Comment by seriouz** [comment] 2023-06-22 15:30
Nice PR! I'll test it

**Comment by seriouz** [comment] 2023-06-22 19:52
@Akshat55 I've tested it and it is working flawlessly! Thank you ❤

The only thing that i currently get is this warning:

```
Warning: E:\Code\test\node_modules\carbon-components-angular\fesm2020\carbon-components-angular-datepicker.mjs depends on 'flatpickr/dist/l10n/index'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by cuauhfer** [comment] 2023-06-28 17:23
I'm also getting the same warnings
```
Warning: path\node_modules\carbon-components-angular\fesm2020\carbon-components-angular-datepicker.mjs depends on 'flatpickr/dist/l10n/index'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: path\node_modules\carbon-components-angular\fesm2020\carbon-components-angular-datepicker.mjs depends on 'flatpickr/dist/plugins/rangePlugin'. CommonJS or AMD dependencies can cause optimization bailouts.       
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Is any way to fix them or any fix in progress?

**Comment by Akshat55** [comment] 2023-07-13 18:17
@cuauhfer I don't think that is something we will be able to fix anytime soon... this is caused by flatpickr library (third-party) which we was chosen by Carbon for datepicker component.

I'll continue to monitor it in future Angular releases but for the time being, I don't think we can remove it and make it a peer dependency.

**Comment by Akshat55** [comment] 2023-07-13 21:31
Closing this PR since v11 is now available.

**Closed by Akshat55** 2023-07-13 21:31 UTC
