### ISSUE TITLE
Structured List: Hover disappears going from item to item

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon-components-angular#1212] opened 2020-04-21 18:07 UTC
## Detailed description

> Describe in detail the issue you're having.

I'm using the Structured List component and I noticed that hovering items with the mouse causes the item bottom border to disappear in certain cases and then to come back eventually.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Structure List

> What did you expect to happen? What happened instead? What would you like to see changed?

Border should stay

> What browser are you working in?

Chrome Version 80.0.3987.163 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

3.46.5
Also happening in the official Storybook

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM AD

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/?path=/story/components-structured-list--with-selection
2. Hover over the first row
3. Move hover down to the second row
4. Move hover down to below the component
5. The border between row 1 and 2 is now gone

## Additional information

Initial
![image](https://user-images.githubusercontent.com/1253469/79898554-6c84b600-83d9-11ea-8ef6-4fd807e84899.png)

After executing the steps above
![image](https://user-images.githubusercontent.com/1253469/79898500-5c6cd680-83d9-11ea-966d-2a8509bf3607.png)

**Comment by cal-smith** [comment] 2020-05-15 17:24
This appears to either be a browser or CSS bug since I can only reproduce it in Chrome and I can reproduce it on components-react as well. Definitly open an issue over on carbon-design-system/carbon for this as well :+1:

**Comment by Akshat55** [comment] 2024-01-25 20:11
No longer reproducible in latest version of chrome, closing this issue since we no longer support or recommend using v3.

**Closed by Akshat55** 2024-01-25 20:11 UTC
Labels: bug, style
